version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/materialious"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/materialious/electron"
    schedule:
      interval: "weekly"
